package config

import "os"

var (
	PORT, PAYMENTS_PROCESSOR_URL_DEFAULT, PAYMENTS_PROCESSOR_URL_FALLBACK string
	HEALTH_PROCESSOR_URL_DEFAULT, HEALTH_PROCESSOR_URL_FALLBACK           string
	PAYMENT_PROCESSOR_TAX_DEFAULT, PAYMENT_PROCESSOR_TAX_FALLBACK         float32
)

func LoadEnv() {
	PORT = os.Getenv("PORT")
	if PORT == "" {
		PORT = "9999"
	}
	PAYMENTS_PROCESSOR_URL_DEFAULT = os.Getenv("PAYMENTS_PROCESSOR_URL_DEFAULT")
	PAYMENTS_PROCESSOR_URL_FALLBACK = os.Getenv("PAYMENTS_PROCESSOR_URL_FALLBACK")
	HEALTH_PROCESSOR_URL_DEFAULT = os.Getenv("HEALTH_PROCESSOR_URL_DEFAULT")
	HEALTH_PROCESSOR_URL_FALLBACK = os.Getenv("HEALTH_PROCESSOR_URL_FALLBACK")
	PAYMENT_PROCESSOR_TAX_DEFAULT = 0.05
	PAYMENT_PROCESSOR_TAX_FALLBACK = 0.15
}
